# Generated by Django 5.2.9 on 2026-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("excused", "Excused"),
                ],
                default="present",
                max_length=10,
            ),
        ),
    ]
