# Generated by Django 5.2.9 on 2026-02-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
    ]
