# Generated by Django 5.0.14 on 2026-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="image",
            field=models.FileField(upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="received_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
