# Generated by Django 5.2.9 on 2026-02-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_certificate_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="centersettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
