# Generated by Django 5.2.9 on 2026-02-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uploadedimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedImage",
        ),
    ]
