# Generated by Django 5.0.14 on 2026-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
