# Generated by Django 5.2.9 on 2026-01-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_delete_paymentsystem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Payment", "verbose_name_plural": "Payments"},
        ),
    ]
